### PR TITLE
generate face initial implementations

### PR DESCRIPTION
**Pull request by MansourHamidi**

### CODE REVIEW

**Comment by MansourHamidi** [comment]
Generating faces is now complete. Depending on the talent of a player, the fatness and the mouth will change - the more talented a player, the happier and thinner his face. The remaining attributes (hair, face color, eyes, ...) are initially generated randomly and then saved into the db; thus, a player does not change his hairstyle or face color during his lifetime.

**Comment by HappyEmu** [comment]
Very nice, will merge soon when I have the time to test.

**Comment by HappyEmu** [comment]
Very nice indeed! :+1:

**Comment by MansourHamidi** [comment]
Thanks bro. Was also your work :-)

**Pull request merged**
